Modifying load_fofn in chunk_fasts.py
nanoporetech/sockeye pull request #16
Opened 2022-08-03 15:27 UTC by tomouellette

Modifying load_fofn to ensure that only files that contain .fastq in their name are included in the list of valid files. The reason for this change is hidden files, e.g. .DS_store, will be included in fofn.txt which causes chunk_fastqs.py to fail via the assertation "Unexpected mixture of file extensions in FOFN" (line 178 in chunk_fastqs.py)

2022-08-03 23:22 UTC, jbeaulaurier requested changes
Hi Tom,
Thanks for the good suggestion. I like the idea, but also want to be sure we allow *.fq, *fastq.gz, and *.fq.gz files.
Best,
John

2022-08-03 23:22 UTC, jbeaulaurier commented on scripts/chunk_fastqs.py
> +        if fastq_ext in path:
We also need to allow *.fq, *.fq.gz, and *.fastq.gz files to be added to the FOFN.

2022-08-05 22:04 UTC, tomouellette commented
Bump, added all suggested filename extensions, as shown here https://github.com/nanoporetech/sockeye/pull/16/files

2022-08-11 22:34 UTC, jbeaulaurier approved these changes

2022-08-11 22:34 UTC, merged